local _, DelCraft = ...

DelCraft.out = {
	["aquadynamic fish attractor"] = 3,
	["arcane bomb"] = 3,
	["arcanite skeleton key"] = 2,
	["big bronze bomb"] = 3,
	["big iron bomb"] = 2,
	["blue firework"] = 3,
	["blue rocket cluster"] = 3,
	["coarse dynamite"] = 2,
	["dark iron bomb"] = 3,
	["dense dynamite"] = 2,
	["ez-thro dynamite"] = 2,
	["gold power core"] = 3,
	["golden skeleton key"] = 2,
	["green firework"] = 3,
	["green rocket cluster"] = 3,
	["heavy dynamite"] = 3,
	["hi-explosive bomb"] = 4,
	["iron buckle"] = 2,
	["iron grenade"] = 3,
	["large blue rocket"] = 3,
	["large blue rocket cluster"] = 3,
	["large green rocket"] = 3,
	["large green rocket cluster"] = 3,
	["large red rocket"] = 3,
	["large red rocket cluster"] = 3,
	["large copper bomb"] = 3,
	["mithril frag bomb"] = 3,
	["red firework"] = 3,
	["red rocket cluster"] = 3,
	["rough copper bomb"] = 2,
	["silver contact"] = 5,
	["silver skeleton key"] = 2,
	["small blue rocket"] = 3,
	["small bronze bomb"] = 2,
	["small green rocket"] = 3,
	["small red rocket"] = 3,
	["snake burst firework"] = 4,
	["solid dynamite"] = 2,
	["the big one"] = 2,
	["thorium grenade"] = 3,
	["truesilver skeleton key"] = 2,
}

DelCraft.adj = {
	-- CLOTH
	["bolt of linen cloth"] = {},
	["bolt of mageweave"] = {},
	["bolt of runecloth"] = {},
	["bolt of silk cloth"] = {},
	["bolt of wollen cloth"] = {},
	["felcloth"] = {},
	["linen cloth"] = {},
	["mageweave cloth"] = {},
	["runecloth"] = {},
	["silk cloth"] = {},
	["wool cloth"] = {},
	-- HERB
	["arthas' tears"] = {},
	["black lotus"] = {},
	["blindweed"] = {},
	["bloodvine"] = {},
	["briarthorn"] = {},
	["bruiseweed"] = {},
	["dreamfoil"] = {},
	["earthroot"] = {},
	["fadeleaf"] = {},
	["firebloom"] = {},
	["ghost mushroom"] = {},
	["golden sansam"] = {},
	["goldthorn"] = {},
	["grave moss"] = {},
	["gromsblood"] = {},
	["icecap"] = {},
	["khadgar's whisker"] = {},
	["kingsblood"] = {},
	["liferoot"] = {},
	["mageroyal"] = {},
	["mountain silversage"] = {},
	["peacebloom"] = {},
	["plaguebloom"] = {},
	["purple lotus"] = {},
	["silverleaf"] = {},
	["stranglekelp"] = {},
	["sungrass"] = {},
	["swiftthistle"] = {},
	["wild steelbloom"] = {},
	["wildvine"] = {},
	["wintersbite"] = {},
	-- LEATHER
	["black dragonscale"] = {},
	["black whelp scale"] = {},
	["blue dragonscale"] = {},
	["core leather"] = {},
	["cured heavy hide"] = {},
	["cured light hide"] = {},
	["cured medium hide"] = {},
	["cured rugged hide"] = {},
	["cured thick hide"] = {},
	["devilsaur leather"] = {},
	["dreamscale"] = {},
	["green dragonscale"] = {},
	["green whelp scale"] = {},
	["heavy leather"] = {},
	["heavy scorpid scale"] = {},
	["light leather"] = {},
	["medium leather"] = {},
	["primal bat leather"] = {},
	["primal tiger leather"] = {},
	["raptor hide"] = {},
	["red dragonscale"] = {},
	["rugged leather"] = {},
	["scale of onyxia"] = {},
	["scorpid scale"] = {},
	["slimy murloc scale"] = {},
	["thick leather"] = {},
	["thick murloc scale"] = {},
	["thin kodo leather"] = {},
	["turtle scale"] = {},
	["warbear leather"] = {},
	["worn dragonscale"] = {},
	-- METAL
	["bronze bar"] = {},
	["copper bar"] = {},
	["dark iron bar"] = {},
	["elementium bar"] = {
		["elementium ore"] = 1,
		["arcanite bar"] = 10,
		["fiery core"] = 1,
		["elemental flux"] = 3,
	},
	["elementium ore"] = {},
	["gold bar"] = {},
	["iron bar"] = {},
	["mithril bar"] = {},
	["mithril ore"] = {},
	["silver bar"] = {},
	["steel bar"] = {},
	["thorium bar"] = {},
	["truesilver bar"] = {},
	-- MISC
	["black dye"] = {},
	["black pearl"] = {},
	["blank parchment"] = {},
	["blood of heroes"] = {},
	["blue pearl"] = {},
	["breath of wind"] = {},
	["coarse thread"] = {},
	["copper rod"] = {},
	["core of earth"] = {},
	["crystal vial"] = {},
	["dark rune"] = {},
	["deeprock salt"] = {},
	["demonic rune"] = {},
	["deviate fish"] = {},
	["discolored worg heart"] = {},
	["elemental air"] = {},
	["elemental earth"] = {},
	["elemental fire"] = {},
	["elemental flux"] = {
		["gold"] = 15,
	},
	["elemental water"] = {},
	["engineer's ink"] = {},
	["empty vial"] = {},
	["essence of air"] = {},
	["essence of earth"] = {},
	["essence of fire"] = {},
	["essence of undeath"] = {},
	["essence of water"] = {},
	["fiery core"] = {},
	["fine thread"] = {},
	["firefin snapper"] = {},
	["flask of mojo"] = {},
	["flask of oil"] = {},
	["frozen rune"] = {},
	["fused wiring"] = {},
	["globe of water"] = {},
	["gold"] = {},
	["golden pearl"] = {},
	["green dye"] = {},
	["guardian stone"] = {},
	["heart of fire"] = {},
	["heart of the wild"] = {},
	["heavy silken thread"] = {},
	["heavy stock"] = {},
	["ichor of undeath"] = {},
	["iridescent pearl"] = {},
	["ironweb spider silk"] = {},
	["jet black feather"] = {},
	["large venom sac"] = {},
	["lava core"] = {},
	["leaded vial"] = {},
	["living essence"] = {},
	["nightcrawlers"] = {},
	["massive mojo"] = {},
	["oily blackmouth"] = {},
	["powerful mojo"] = {},
	["purple dye"] = {},
	["refreshing spring water"] = {},
	["rune thread"] = {},
	["shadow silk"] = {},
	["sharp claw"] = {},
	["silken thread"] = {},
	["skin of shadow"] = {},
	["snowball"] = {},
	["small flame sac"] = {},
	["spider silk"] = {},
	["stonescale eel"] = {},
	["strong flux"] = {},
	["sulfuron ingot"] = {},
	["thick spider silk"] = {},
	["volatile rum"] = {},
	["weak flux"] = {},
	["wooden stock"] = {},
	["yellow power crystal"] = {},
	["red power crystal"] = {},
	["green power crystal"] = {},
	["blue power crystal"] = {},
	-- STONES
	["aquamarine"] = {},
	["azerothian diamond"] = {},
	["black diamond"] = {},
	["black vitriol"] = {},
	["blood of the mountain"] = {},
	["blue sapphire"] = {},
	["citrine"] = {},
	["coarse stone"] = {},
	["dense stone"] = {},
	["heavy stone"] = {},
	["huge emerald"] = {},
	["jade"] = {},
	["large obsidian shard"] = {},
	["large opal"] = {},
	["lesser moonstone"] = {},
	["malachite"] = {},
	["moss agate"] = {},
	["rough stone"] = {},
	["shadow gem"] = {},
	["small obsidian shard"] = {},
	["solid stone"] = {},
	["souldarite"] = {},
	["star ruby"] = {},
	["tigerseye"] = {},
	-- ALCHEMY
	["arcane elixir"] = {
		["blindweed"] = 1,
		["goldthorn"] = 1,
		["crystal vial"] = 1,
	},
	["arcanite bar"] = {},
	["blackmouth oil"] = {
		["oily blackmouth"] = 2,
		["empty vial"] = 1,
	},
	["catseye elixir"] = {
		["goldthorn"] = 1,
		["fadeleaf"] = 1,
		["leaded vial"] = 1,
	},
	["discolored healing potion"] = {
		["discolored worg heart"] = 1,
		["peacebloom"] = 1,
		["empty vial"] = 1,
	},
	["dreamless sleep potion"] = {
		["purple lotus"] = 3,
		["crystal vial"] = 1,
	},
	["elixir of agility"] = {
		["stranglekelp"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of brute force"] = {
		["gromsblood"] = 2,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["elixir of defense"] = {
		["wild steelbloom"] = 1,
		["stranglekelp"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of demonslaying"] = {
		["gromsblood"] = 1,
		["ghost mushroom"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of detect demon"] = {
		["gromsblood"] = 2,
		["crystal vial"] = 1,
	},
	["elixir of detect lesser invisibility"] = {
		["khadgar's whisker"] = 1,
		["fadeleaf"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of detect undead"] = {
		["arthas' tears"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of dream vision"] = {
		["purple lotus"] = 3,
		["crystal vial"] = 1,
	},
	["elixir of firepower"] = {
		["fire oil"] = 2,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of fortitude"] = {
		["wild steelbloom"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of frostpower"] = {
		["wintersbite"] = 2,
		["khadgar's whisker"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of giant growth"] = {
		["deviate fish"] = 1,
		["earthroot"] = 1,
		["empty vial"] = 1,
	},
	["elixir of giants"] = {
		["sungrass"] = 1,
		["gromsblood"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of greater agility"] = {
		["sungrass"] = 1,
		["goldthorn"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of greater defense"] = {
		["wild steelbloom"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of greater firepower"] = {
		["fire oil"] = 3,
		["firebloom"] = 3,
		["crystal vial"] = 1,
	},
	["elixir of greater intellect"] = {
		["blindweed"] = 1,
		["khadgar's whisker"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of greater waterbreathing"] = {
		["ichor of undeath"] = 1,
		["purple lotus"] = 2,
		["crystal vial"] = 1,
	},
	["elixir of lesser agility"] = {
		["wild steelbloom"] = 1,
		["swiftthistle"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of lion's strength"] = {
		["earthroot"] = 1,
		["silverleaf"] = 1,
		["empty vial"] = 1,
	},
	["elixir of minor agility"] = {
		["swiftthistle"] = 1,
		["silverleaf"] = 1,
		["empty vial"] = 1,
	},
	["elixir of minor defense"] = {
		["silverleaf"] = 2,
		["empty vial"] = 1,
	},
	["elixir of minor fortitude"] = {
		["earthroot"] = 2,
		["peacebloom"] = 1,
		["empty vial"] = 1,
	},
	["elixir of ogre's strength"] = {
		["earthroot"] = 1,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of poison resistance"] = {
		["large venom sac"] = 1,
		["bruiseweed"] = 1,
		["leaded vial"] = 1,
	},
	["elixir of shadow power"] = {
		["ghost mushroom"] = 3,
		["crytal vial"] = 1,
	},
	["elixir of superior defense"] = {
		["stonescale oil"] = 2,
		["sungrass"] = 1,
		["crystal vial"] = 1,
	},
	["elixir of the mongoose"] = {
		["mountain silversage"] = 2,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["elixir of the sages"] = {
		["dreamfoil"] = 1,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["elixir of waterbreathing"] = {
		["stranglekelp"] = 1,
		["blackmouth oil"] = 2,
		["empty vial"] = 1,
	},
	["elixir of wisdom"] = {
		["mageroyal"] = 1,
		["briarthorn"] = 2,
		["empty vial"] = 1,
	},
	["fire oil"] = {
		["firefin snapper"] = 2,
		["empty vial"] = 1,
	},
	["fire protection potion"] = {
		["small flame sac"] = 1,
		["fire oil"] = 1,
		["leaded vial"] = 1,
	},
	["flask of chromatic resistance"] = {
		["icecap"] = 30,
		["mountain silversage"] = 10,
		["black lotus"] = 1,
		["crystal vial"] = 1,
	},
	["flask of distilled wisdom"] = {
		["dreamfoil"] = 30,
		["icecap"] = 10,
		["black lotus"] = 1,
		["crystal vial"] = 1,
	},
	["flask of petrification"] = {
		["stonescale oil"] = 30,
		["mountain silversage"] = 10,
		["black lotus"] = 1,
		["crystal vial"] = 1,
	},
	["flask of supreme power"] = {
		["dreamfoil"] = 30,
		["mountain silversage"] = 10,
		["black lotus"] = 1,
		["crystal vial"] = 1,
	},
	["flask of the titans"] = {
		["gromsblood"] = 30,
		["stonescale oil"] = 10,
		["black lotus"] = 1,
		["crystal vial"] = 1,
	},
	["free action potion"] = {
		["blackmouth oil"] = 2,
		["stranglekelp"] = 1,
		["leaded vial"] = 1,
	},
	["frost oil"] = {
		["khadgar's whisker"] = 4,
		["wintersbite"] = 2,
		["leaded vial"] = 1,
	},
	["frost protection potion"] = {
		["wintersbite"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["ghost dye"] = {
		["ghost mushroom"] = 2,
		["purple dye"] = 1,
		["crystal vial"] = 1,
	},
	["gift of arthas"] = {
		["arthas' tears"] = 1,
		["blindweed"] = 1,
		["crystal vial"] = 1,
	},
	["goblin rocket fuel"] = {
		["firebloom"] = 1,
		["volatile rum"] = 1,
		["leaded vial"] = 1,
	},
	["great rage potion"] = {
		["large fang"] = 1,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["greater arcane elixir"] = {
		["dreamfoil"] = 3,
		["mountain silversage"] = 1,
		["crystal vial"] = 1,
	},
	["greater arcane protection potion"] = {
		["dream dust"] = 1,
		["dreamfoil"] = 1,
		["crystal vial"] = 1,
	},
	["greater dreamless sleep potion"] = {
		["dreamfoil"] = 2,
		["golden sansam"] = 1,
		["crystal vial"] = 1,
	},
	["greater fire protection potion"] = {
		["elemental fire"] = 1,
		["dreamfoil"] = 1,
		["crystal vial"] = 1,
	},
	["greater frost protection potion"] = {
		["elemental water"] = 1,
		["dreamfoil"] = 1,
		["crystal vial"] = 1,
	},
	["greater healing potion"] = {
		["liferoot"] = 1,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["greater mana potion"] = {
		["khadgar's whisker"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["greater nature protection potion"] = {
		["elemental earth"] = 1,
		["dreamfoil"] = 1,
		["crystal vial"] = 1,
	},
	["greater shadow protection potion"] = {
		["shadow oil"] = 1,
		["dreamfoil"] = 1,
		["crystal vial"] = 1,
	},
	["gurubashi mojo madness"] = {
		["blood of heroes"] = 1,
		["massive mojo"] = 1,
		["powerful mojo"] = 6,
		["black lotus"] = 1,
	},
	["healing potion"] = {
		["bruiseweed"] = 1,
		["briarthorn"] = 1,
		["leaded vial"] = 1,
	},
	["holy protection potion"] = {
		["bruiseweed"] = 1,
		["swiftthistle"] = 1,
		["empty vial"] = 1,
	},
	["invisibility potion"] = {
		["ghost mushroom"] = 1,
		["sungrass"] = 1,
		["crystal vial"] = 1,
	},
	["lesser arcane elixir"] = {
		["kingsblood"] = 1,
		["goldthorn"] = 1,
		["crystal vial"] = 1,
	},
	["lesser healing potion"] = {
		["minor healing potion"] = 1,
		["briarthorn"] = 1,
	},
	["lesser invisibility potion"] = {
		["fadeleaf"] = 1,
		["wild steelbloom"] = 1,
		["leaded vial"] = 1,
	},
	["lesser mana potion"] = {
		["mageroyal"] = 1,
		["stranglekelp"] = 1,
		["empty vial"] = 1,
	},
	["lesser stoneshield potion"] = {
		["mithril ore"] = 1,
		["goldthorn"] = 1,
		["leaded vial"] = 1,
	},
	["limited invulnerability potion"] = {
		["blindweed"] = 2,
		["ghost mushroom"] = 1,
		["crystal vial"] = 1,
	},
	["living action potion"] = {
		["icecap"] = 2,
		["mountain silversage"] = 2,
		["khadgar's whisker"] = 2,
		["crystal vial"] = 1,
	},
	["mageblood potion"] = {
		["dreamfoil"] = 1,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["magic resistance potion"] = {
		["khadgar's whisker"] = 1,
		["purple lotus"] = 1,
		["crystal vial"] = 1,
	},
	["major healing potion"] = {
		["golden sansam"] = 2,
		["mountain silversage"] = 1,
		["crystal vial"] = 1,
	},
	["major mana potion"] = {
		["dreamfoil"] = 3,
		["icecap"] = 2,
		["crystal vial"] = 1,
	},
	["major rejuvenation potion"] = {
		["khadgar's whisper"] = 1,
		["golden sansam"] = 4,
		["dreamfoil"] = 4,
		["crystal vial"] = 1,
	},
	["major troll's blood potion"] = {
		["gromsblood"] = 1,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["mana potion"] = {
		["stranglekelp"] = 1,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["mighty rage potion"] = {
		["gromsblood"] = 3,
		["crystal vial"] = 1,
	},
	["mighty troll's blood potion"] = {
		["liferoot"] = 1,
		["bruiseweed"] = 1,
		["leaded vial"] = 1,
	},
	["minor healing potion"] = {
		["peacebloom"] = 1,
		["silverleaf"] = 1,
		["empty vial"] = 1,
	},
	["minor magic resistance potion"] = {
		["mageroyal"] = 3,
		["wild steelbloom"] = 1,
		["empty vial"] = 1,
	},
	["minor mana potion"] = {
		["mageroyal"] = 1,
		["silverleaf"] = 1,
		["empty vial"] = 1,
	},
	["minor rejuvenation potion"] = {
		["mageroyal"] = 2,
		["peacebloom"] = 1,
		["empty vial"] = 1,
	},
	["nature protection potion"] = {
		["liferoot"] = 1,
		["stranglekelp"] = 1,
		["leaded vial"] = 1,
	},
	["oil of immolation"] = {
		["firebloom"] = 1,
		["goldthorn"] = 1,
		["crystal vial"] = 1,
	},
	["philosopher's stone"] = {
		["iron bar"] = 4,
		["black vitriol"] = 1,
		["purple lotus"] = 4,
		["firebloom"] = 4,
	},
	["purification potion"] = {
		["icecap"] = 2,
		["plaguebloom"] = 2,
		["crystal vial"] = 1,
	},
	["rage potion"] = {
		["sharp claw"] = 1,
		["briarthorn"] = 1,
		["empty vial"] = 1,
	},
	["restorative potion"] = {
		["elemental earth"] = 1,
		["goldthorn"] = 1,
		["crystal vial"] = 1,
	},
	["shadow oil"] = {
		["fadeleaf"] = 4,
		["grave moss"] = 4,
		["leaded vial"] = 1,
	},
	["shadow protection potion"] = {
		["grave moss"] = 1,
		["kingsblood"] = 1,
		["leaded vial"] = 1,
	},
	["stonescale oil"] = {
		["stonescale eel"] = 1,
		["leaded vial"] = 1,
	},
	["strong troll's blood potion"] = {
		["bruiseweed"] = 2,
		["briarthorn"] = 2,
		["leaded vial"] = 1,
	},
	["superior healing potion"] = {
		["sungrass"] = 1,
		["khadgar's whisker"] = 1,
		["crystal vial"] = 1,
	},
	["superior mana potion"] = {
		["sungrass"] = 2,
		["blindweed"] = 2,
		["crystal vial"] = 1,
	},
	["swiftness potion"] = {
		["swiftthistle"] = 1,
		["briarthorn"] = 1,
		["empty vial"] = 1,
	},
	["swim speed potion"] = {
		["swiftthistle"] = 1,
		["blackmouth oil"] = 1,
		["empty vial"] = 1,
	},
	["weak troll's blood potion"] = {
		["peacebloom"] = 1,
		["earthroot"] = 2,
		["empty vial"] = 1,
	},
	["wildvine potion"] = {
		["kingsblood"] = 1,
		["purple lotus"] = 1,
		["crystal vial"] = 1,
	},
	-- BLACKSMITHING
	["annihilator"] = {
		["thorium bar"] = 40,
		["arcanite bar"] = 12,
		["essence of undeath"] = 10,
		["huge emerald"] = 8,
		["dense grinding stone"] = 2,
		["enchanted leather"] = 4,
	},
	["arcanite champion"] = {
		["arcanite bar"] = 15,
		["azerothian diamond"] = 8,
		["righteous orb"] = 1,
		["large opal"] = 4,
		["enchanted leather"] = 8,
		["dense grinding stone"] = 2,
	},
	["arcanite reaper"] = {
		["arcanite bar"] = 20,
		["enchanted leather"] = 6,
		["dense grinding stone"] = 2,
	},
	["arcanite rod"] = {
		["arcanite bar"] = 3,
		["dense grinding stone"] = 1,
	},
	["arcanite skeleton key"] = {
		["arcanite bar"] = 1,
		["dense grinding stone"] = 1,
	},
	["barbaric iron boots"] = {
		["iron bar"] = 12,
		["large fang"] = 4,
		["tigerseye"] = 4,
		["heavy grinding stone"] = 2,
	},
	["barbaric iron breastplate"] = {
		["iron bar"] = 20,
		["heavy grinding stone"] = 4,
	},
	["barbaric iron gloves"] = {
		["iron bar"] = 14,
		["heavy grinding stone"] = 3,
		["large fang"] = 2,
	},
	["barbaric iron helm"] = {
		["iron bar"] = 10,
		["large fang"] = 2,
		["sharp claw"] = 2,
	},
	["barbaric iron shoulders"] = {
		["iron bar"] = 8,
		["sharp claw"] = 4,
		["shadowgem"] = 2,
		["heavy grinding stone"] = 2,
	},
	["big black mace"] = {
		["mithril bar"] = 16,
		["black pearl"] = 1,
		["shadow gem"] = 4,
		["heavy grinding stone"] = 1,
		["thick leather"] = 2,
	},
	["big bronze knife"] = {
		["bronze bar"] = 6,
		["weak flux"] = 4,
		["rough grinding stone"] = 2,
		["tigerseye"] = 1,
		["medium leather"] = 1,
	},
	["black amnesty"] = {
		["lava core"] = 3,
		["fiery core"] = 6,
		["arcanite bar"] = 12,
		["blood of the mountain"] = 1,
		["dark iron bar"] = 4,
	},
	["black grasp of the destroyer"] = {
		["large obsidian shard"] = 8,
		["small obsidian shard"] = 24,
		["enchanted leather"] = 8,
		["flask of supreme power"] = 1,
	},
	["blackfury"] = {
		["lava core"] = 5,
		["fiery core"] = 2,
		["arcanite bar"] = 16,
		["dark iron bar"] = 6,
	},
	["blackguard"] = {
		["lava core"] = 6,
		["fiery core"] = 6,
		["arcanite bar"] = 10,
		["dark iron bar"] = 6,
		["guardian stone"] = 12,
	},
	["blazing rapier"] = {
		["enchanted thorium bar"] = 10,
		["essence of fire"] = 4,
		["heart of fire"] = 4,
		["azerothian diamond"] = 2,
		["dense grinding stone"] = 2,
	},
	["blight"] = {
		["mithril bar"] = 28,
		["ichor of undeath"] = 10,
		["truesilver bar"] = 10,
		["solid grinding stone"] = 6,
		["thick leather"] = 6,
	},
	["bloodsoul breastplate"] = {
		["thorium bar"] = 20,
		["souldarite"] = 10,
		["bloodvine"] = 2,
		["star ruby"] = 2,
	},
	["bloodsoul gauntlets"] = {
		["thorium bar"] = 12,
		["souldarite"] = 6,
		["bloodvine"] = 2,
		["enchanted leather"] = 4,
	},
	["bloodsoul shoulders"] = {
		["thorium bar"] = 16,
		["souldarite"] = 8,
		["bloodvine"] = 2,
		["star ruby"] = 1,
	},
	["blue glittering axe"] = {
		["mithril bar"] = 16,
		["aquamarine"] = 2,
		["solid grinding stone"] = 1,
		["thick leather"] = 4,
	},
	["bronze axe"] = {
		["bronze bar"] = 7,
		["weak flux"] = 4,
		["medium leather"] = 1,
	},
	["bronze battle axe"] = {
		["bronze bar"] = 14,
		["strong flux"] = 1,
		["medium leather"] = 2,
	},
	["bronze greatsword"] = {
		["bronze bar"] = 12,
		["strong flux"] = 2,
		["medium leather"] = 2,
	},
	["bronze mace"] = {
		["bronze bar"] = 6,
		["weak flux"] = 4,
		["medium leather"] = 1,
	},
	["bronze shortsword"] = {
		["bronze bar"] = 5,
		["weak flux"] = 4,
		["medium leather"] = 2,
	},
	["bronze warhammer"] = {
		["bronze bar"] = 8,
		["strong flux"] = 1,
		["medium leather"] = 1,
	},
	["coarse grinding stone"] = {
		["coarse stone"] = 2,
	},
	["coarse sharpening stone"] = {
		["coarse stone"] = 1,
	},
	["coarse weightstone"] = {
		["coarse stone"] = 1,
		["wool cloth"] = 1,
	},
	["copper axe"] = {
		["copper bar"] = 6,
		["weak flux"] = 1,
		["linen cloth"] = 2,
	},
	["copper battle axe"] = {
		["copper bar"] = 12,
		["weak flux"] = 2,
		["malachite"] = 2,
		["rough grinding stone"] = 2,
		["light leather"] = 2,
	},
	["copper bracers"] = {
		["copper bar"] = 2,
	},
	["copper chain belt"] = {
		["copper bar"] = 6,
	},
	["copper chain boots"] = {
		["copper bar"] = 8,
	},
	["copper chain pants"] = {
		["copper bar"] = 4,
	},
	["copper chain vest"] = {
		["copper bar"] = 8,
		["malachite"] = 1,
		["rough grinding stone"] = 2,
	},
	["copper claymore"] = {
		["copper bar"] = 10,
		["weak flux"] = 2,
		["rough grinding stone"] = 1,
		["light leather"] = 1,
	},
	["copper dagger"] = {
		["copper bar"] = 6,
		["weak flux"] = 1,
		["rough grinding stone"] = 1,
		["light leather"] = 1,
	},
	["copper mace"] = {
		["copper bar"] = 6,
		["weak flux"] = 1,
		["linen cloth"] = 2,
	},
	["copper shortsword"] = {
		["copper bar"] = 6,
		["weak flux"] = 1,
		["linen cloth"] = 2,
	},
	["corruption"] = {
		["thorium bar"] = 40,
		["arcanite bar"] = 2,
		["demonic rune"] = 16,
		["essence of undeath"] = 8,
		["blue sapphire"] = 2,
		["dense grinding stone"] = 2,
		["rugged leather"] = 4,
	},
	["dark iron boots"] = {
		["lava core"] = 3,
		["fiery core"] = 3,
		["core leather"] = 4,
		["dark iron bar"] = 6,
	},
	["dark iron bracers"] = {
		["dark iron bar"] = 4,
		["lava core"] = 2,
		["fiery core"] = 2,
	},
	["dark iron destroyer"] = {
		["dark iron bar"] = 18,
		["lava core"] = 12,
		["blood of the mountain"] = 2,
		["enchanted leather"] = 2,
	},
	["dark iron gauntlets"] = {
		["lava core"] = 3,
		["fiery core"] = 5,
		["core leather"] = 4,
		["dark iron bar"] = 4,
		["blood of the mountain"] = 2,
	},
	["dark iron helm"] = {
		["lava core"] = 4,
		["fiery core"] = 2,
		["dark iron bar"] = 4,
	},
	["dark iron leggings"] = {
		["dark iron bar"] = 16,
		["fiery core"] = 4,
		["lava core"] = 6,
	},
	["dark iron mail"] = {
		["dark iron bar"] = 10,
		["heart of fire"] = 2,
	},
	["dark iron plate"] = {
		["dark iron bar"] = 20,
		["heart of fire"] = 8,
	},
	["dark iron pulverizer"] = {
		["dark iron bar"] = 18,
		["heart of fire"] = 4,
	},
	["dark iron reaver"] = {
		["dark iron bar"] = 16,
		["fiery core"] = 12,
		["blood of the mountain"] = 2,
		["enchanted leather"] = 2,
	},
	["dark iron shoulders"] = {
		["dark iron bar"] = 6,
		["heart of fire"] = 1,
	},
	["dark iron sunderer"] = {
		["dark iron bar"] = 26,
		["heart of fire"] = 4,
	},
	["darkrune breastplate"] = {
		["thorium bar"] = 20,
		["dark rune"] = 10,
		["truesilver bar"] = 10,
	},
	["darkrune gauntlets"] = {
		["thorium bar"] = 12,
		["dark rune"] = 6,
		["truesilver bar"] = 6,
		["enchanted leather"] = 2,
	},
	["darkrune helm"] = {
		["thorium bar"] = 16,
		["dark rune"] = 8,
		["truesilver bar"] = 8,
		["black diamond"] = 1,
	},
	["darksoul breastplate"] = {
		["thorium bar"] = 20,
		["souldarite"] = 14,
		["large opal"] = 2,
	},
	["darksoul leggings"] = {
		["thorium bar"] = 18,
		["souldarite"] = 12,
		["large opal"] = 2,
	},
	["darksoul shoulders"] = {
		["thorium bar"] = 16,
		["souldarite"] = 10,
		["large opal"] = 1,
	},
	["dawn's edge"] = {
		["thorium bar"] = 30,
		["enchanted thorium bar"] = 4,
		["star ruby"] = 4,
		["blue sapphire"] = 4,
		["dense grinding stone"] = 2,
		["rugged leather"] = 4,
	},
	["dazzling mithril rapier"] = {
		["mithril bar"] = 14,
		["aquamarine"] = 1,
		["lesser moonstone"] = 2,
		["moss agate"] = 2,
		["solid grinding stone"] = 1,
		["mageweave cloth"] = 2,
	},
	["deadly bronze poniard"] = {
		["bronze bar"] = 4,
		["strong flux"] = 1,
		["swiftness potion"] = 1,
		["shadowgem"] = 2,
		["coarse grinding stone"] = 2,
		["medium leather"] = 2,
	},
	["demon forged breastplate"] = {
		["thorium bar"] = 40,
		["demonic rune"] = 10,
		["blue sapphire"] = 4,
		["star ruby"] = 4,
	},
	["dense grinding stone"] = {
		["dense stone"] = 4,
	},
	["dense sharpening stone"] = {
		["dense stone"] = 1,
	},
	["dense weightstone"] = {
		["dense stone"] = 1,
		["runecloth"] = 1,
	},
	["desecration"] = {
		["thorium bar"] = 40,
		["arcanite bar"] = 2,
		["demonic rune"] = 16,
		["essence of undeath"] = 8,
		["blue sapphire"] = 2,
		["dense grinding stone"] = 2,
		["rugged leather"] = 4,
	},
	["ebon hand"] = {
		["lava core"] = 4,
		["fiery core"] = 7,
		["arcanite bar"] = 12,
		["dark iron bar"] = 8,
		["azerothian diamond"] = 4,
	},
	["ebon shiv"] = {
		["mithril bar"] = 12,
		["truesilver bar"] = 6,
		["star ruby"] = 2,
		["solid grinding stone"] = 1,
		["thick leather"] = 2,
	},
	["edge of winter"] = {
		["steel bar"] = 10,
		["frost oil"] = 1,
		["elemental water"] = 2,
		["elemental air"] = 2,
		["heavy leather"] = 2,
	},
	["elemental sharpening stone"] = {
		["elemental earth"] = 2,
		["dense stone"] = 3,
	},
	["enchanted battlehammer"] = {
		["thorium bar"] = 20,
		["enchanted thorium bar"] = 6,
		["huge emerald"] = 2,
		["powerful mojo"] = 4,
		["rugged leather"] = 4,
	},
	["enchanted thorium breastplate"] = {
		["arcanite bar"] = 8,
		["enchanted thorium bar"] = 24,
		["essence of earth"] = 4,
		["essence of water"] = 4,
		["huge emerald"] = 2,
		["azerothian diamond"] = 2,
	},
	["enchanted thorium helm"] = {
		["arcanite bar"] = 6,
		["enchanted thorium bar"] = 16,
		["essence of earth"] = 6,
		["large opal"] = 2,
		["azerothian diamond"] = 1,
	},
	["enchanted thorium leggings"] = {
		["arcanite bar"] = 10,
		["enchanted thorium bar"] = 20,
		["essence of water"] = 6,
		["blue sapphire"] = 2,
		["huge emerald"] = 1,
	},
	["fiery chain girdle"] = {
		["dark iron bar"] = 6,
		["fiery core"] = 3,
		["lava core"] = 3,
	},
	["fiery chain shoulders"] = {
		["dark iron bar"] = 16,
		["fiery core"] = 4,
		["lava core"] = 5,
	},
	["fiery plate gauntlets"] = {
		["thorium bar"] = 20,
		["enchanted thorium bar"] = 6,
		["essence of fire"] = 2,
		["star ruby"] = 4,
	},
	["finely-enchanted battlehammer"] = {
		["thorium bar"] = 20,
		["enchanted thorium bar"] = 6,
		["huge emerald"] = 2,
		["powerful mojo"] = 4,
		["rugged leather"] = 4,
	},
	["frostguard"] = {
		["arcanite bar"] = 18,
		["blue sapphire"] = 8,
		["azerothian diamond"] = 8,
		["essence of water"] = 4,
		["dense grinding stone"] = 2,
		["enchanted leather"] = 4,
	},
	["gemmed copper gauntlets"] = {
		["copper bar"] = 8,
		["tigerseye"] = 1,
		["malachite"] = 1,
	},
	["girdle of the dawn"] = {
		["thorium bar"] = 6,
		["truesilver bar"] = 6,
		["righteous orb"] = 1,
	},
	["glinting steel dagger"] = {
		["steel bar"] = 10,
		["strong flux"] = 2,
		["moss agate"] = 1,
		["elemental earth"] = 1,
		["heavy leather"] = 1,
	},
	["gloves of the dawn"] = {
		["arcanite bar"] = 2,
		["truesilver bar"] = 10,
		["righteous orb"] = 1,
	},
	["golden rod"] = {
		["gold bar"] = 1,
		["coarse grinding stone"] = 2,
	},
	["golden scale boots"] = {
		["steel bar"] = 10,
		["gold bar"] = 4,
		["heavy grinding stone"] = 4,
		["citrine"] = 1,
	},
	["golden scale bracers"] = {
		["steel bar"] = 5,
		["heavy grinding stone"] = 2,
	},
	["golden scale coif"] = {
		["steel bar"] = 8,
		["gold bar"] = 2,
		["heavy grinding stone"] = 2,
	},
	["golden scale cuirass"] = {
		["steel bar"] = 12,
		["gold bar"] = 2,
		["heavy grinding stone"] = 4,
		["jade"] = 2,
	},
	["golden scale gauntlets"] = {
		["steel bar"] = 10,
		["gold bar"] = 4,
		["heavy grinding stone"] = 4,
		["citrine"] = 1,
	},
	["golden scale leggings"] = {
		["iron bar"] = 10,
		["gold bar"] = 2,
		["heavy grinding stone"] = 1,
	},
	["golden scale shoulders"] = {
		["steel bar"] = 6,
		["gold bar"] = 2,
		["heavy grinding stone"] = 1,
	},
	["golden skeleton key"] = {
		["gold bar"] = 1,
		["heavy grinding stone"] = 1,
	},
	["green iron boots"] = {
		["iron bar"] = 4,
		["lesser moonstone"] = 2,
		["coarse grinding stone"] = 2,
		["green dye"] = 1,
	},
	["green iron bracers"] = {
		["iron bar"] = 6,
		["green dye"] = 1,
	},
	["green iron gauntlets"] = {
		["iron bar"] = 4,
		["small lustrous pearl"] = 2,
		["coarse grinding stone"] = 2,
		["green dye"] = 1,
	},
	["green iron hauberk"] = {
		["iron bar"] = 20,
		["heavy grinding stone"] = 4,
		["jade"] = 2,
		["moss agate"] = 2,
		["green leather armor"] = 1,
	},
	["green iron helm"] = {
		["iron bar"] = 12,
		["citrine"] = 1,
		["green dye"] = 1,
	},
	["green iron leggings"] = {
		["iron bar"] = 8,
		["heavy grinding stone"] = 1,
		["green dye"] = 1,
	},
	["green iron shoulders"] = {
		["iron bar"] = 7,
		["heavy grinding stone"] = 1,
		["green dye"] = 1,
	},
	["hammer of the titans"] = {
		["thorium bar"] = 50,
		["arcanite bar"] = 15,
		["guardian stone"] = 4,
		["enchanted leather"] = 6,
		["essence of earth"] = 10,
	},
	["hardened iron shortsword"] = {
		["iron bar"] = 6,
		["strong flux"] = 2,
		["heavy grinding stone"] = 1,
		["lesser moonstone"] = 2,
		["heavy leather"] = 3,
	},
	["heartseeker"] = {
		["arcanite bar"] = 10,
		["enchanted thorium bar"] = 10,
		["enchanted leather"] = 2,
		["star ruby"] = 6,
		["azerothian diamond"] = 6,
		["large opal"] = 6,
		["heavy grinding stone"] = 4,
	},
	["heavy bronze mace"] = {
		["bronze bar"] = 8,
		["strong flux"] = 1,
		["moss agate"] = 1,
		["shadowgem"] = 1,
		["coarse grinding stone"] = 2,
		["medium leather"] = 2,
	},
	["heavy copper broadsword"] = {
		["copper bar"] = 14,
		["weak flux"] = 2,
		["tigerseye"] = 2,
		["medium leather"] = 2,
	},
	["heavy copper maul"] = {
		["copper bar"] = 12,
		["weak flux"] = 2,
		["light leather"] = 2,
	},
	["heavy grinding stone"] = {
		["heavy stone"] = 3,
	},
	["heavy mithril axe"] = {
		["mithril bar"] = 12,
		["citrine"] = 2,
		["solid grinding stone"] = 1,
		["heavy leather"] = 4,
	},
	["heavy mithril boots"] = {
		["mithril bar"] = 14,
		["thick leather"] = 4,
	},
	["heavy mithril breastplate"] = {
		["mithril bar"] = 16,
	},
	["heavy mithril gauntlet"] = {
		["mithril bar"] = 6,
		["mageweave cloth"] = 4,
	},
	["heavy mithril helm"] = {
		["mithril bar"] = 14,
		["aquamarine"] = 1,
	},
	["heavy mithril pants"] = {
		["mithril bar"] = 10,
		["lesser moonstone"] = 2,
	},
	["heavy mithril shoulder"] = {
		["mithril bar"] = 8,
		["heavy leather"] = 6,
	},
	["heavy obsidian belt"] = {
		["small obsidian shard"] = 14,
		["enchanted thorium bar"] = 4,
		["essence of earth"] = 2,
	},
	["heavy sharpening stone"] = {
		["heavy stone"] = 1,
	},
	["heavy timbermaw belt"] = {
		["thorium bar"] = 12,
		["essence of earth"] = 3,
		["living essence"] = 3,
	},
	["heavy timbermaw boots"] = {
		["arcanite bar"] = 4,
		["essence of earth"] = 6,
		["living essence"] = 6,
	},
	["heavy weightstone"] = {
		["heavy stone"] = 1,
		["wool cloth"] = 1,
	},
	["helm of the great chief"] = {
		["thorium bar"] = 40,
		["enchanted thorium bar"] = 4,
		["jet black feather"] = 60,
		["large opal"] = 6,
		["huge emerald"] = 2,
	},
	["huge thorium battle axe"] = {
		["thorium bar"] = 40,
		["dense grinding stone"] = 6,
		["rugged leather"] = 6,
	},
	["icebane bracers"] = {
		["frozen rune"] = 4,
		["thorium bar"] = 12,
		["arcanite bar"] = 2,
		["essence of water"] = 2,
	},
	["icebane breastplate"] = {
		["frozen rune"] = 7,
		["thorium bar"] = 16,
		["arcanite bar"] = 2,
		["essence of water"] = 4,
	},
	["icebane gauntlets"] = {
		["frozen rune"] = 5,
		["thorium bar"] = 12,
		["arcanite bar"] = 2,
		["essence of water"] = 2,
	},
	["imperial plate belt"] = {
		["thorium bar"] = 22,
		["rugged leather"] = 6,
		["aquamarine"] = 1,
	},
	["imperial plate boots"] = {
		["thorium bar"] = 34,
		["star ruby"] = 1,
		["aquamarine"] = 1,
	},
	["imperial plate bracers"] = {
		["thorium bar"] = 20,
		["star ruby"] = 1,
	},
	["imperial plate chest"] = {
		["thorium bar"] = 40,
		["star ruby"] = 2,
	},
	["imperial plate helm"] = {
		["thorium bar"] = 34,
		["star ruby"] = 2,
	},
	["imperial plate leggings"] = {
		["thorium bar"] = 44,
		["star ruby"] = 2,
	},
	["imperial plate shoulders"] = {
		["thorium bar"] = 24,
		["rugged leather"] = 6,
		["citrine"] = 2,
	},
	["inlaid mithril cylinder"] = {
		["mithril bar"] = 5,
		["gold bar"] = 1,
		["truesilver bar"] = 1,
	},
	["invulnerable mail"] = {
		["arcanite bar"] = 30,
		["enchanted thorium bar"] = 30,
		["huge emerald"] = 6,
		["azerothian diamond"] = 6,
	},
	["iridescent hammer"] = {
		["bronze bar"] = 10,
		["strong flux"] = 1,
		["iridescent pearl"] = 1,
		["coarse grinding stone"] = 2,
		["medium leather"] = 2,
	},
	["iron buckle"] = {
		["iron bar"] = 1,
	},
	["iron counterweight"] = {
		["iron bar"] = 4,
		["coarse grinding stone"] = 2,
		["lesser moonstone"] = 1,
	},
	["iron shield spike"] = {
		["iron bar"] = 6,
		["coarse grinding stone"] = 4,
	},
	["ironforge breastplate"] = {
		["copper bar"] = 16,
		["tigerseye"] = 2,
		["coarse grinding stone"] = 3,
	},
	["ironvine belt"] = {
		["enchanted thorium bar"] = 6,
		["living essence"] = 2,
	},
	["ironvine breastplate"] = {
		["enchanted thorium bar"] = 12,
		["bloodvine"] = 2,
		["arcanite bar"] = 2,
		["living essence"] = 2,
	},
	["ironvine gloves"] = {
		["enchanted thorium bar"] = 8,
		["bloodvine"] = 1,
		["living essence"] = 2,
	},
	["jade serpentblade"] = {
		["iron bar"] = 8,
		["strong flux"] = 2,
		["heavy grinding stone"] = 2,
		["jade"] = 2,
		["heavy leather"] = 3,
	},
	["jagged obsidian shield"] = {
		["large obsidian shard"] = 8,
		["small obsidian shard"] = 24,
		["enchanted thorium bar"] = 8,
		["essence of earth"] = 4,
	},
	["light obsidian belt"] = {
		["small obsidian shard"] = 14,
		["enchanted leather"] = 4,
	},
	["lionheart helm"] = {
		["thorium bar"] = 80,
		["arcanite bar"] = 12,
		["wicked claw"] = 40,
		["blue sapphire"] = 10,
		["azerothian diamond"] = 4,
	},
	["masterwork stormhammer"] = {
		["enchanted thorium bar"] = 20,
		["huge emerald"] = 8,
		["large opal"] = 8,
		["essence of earth"] = 6,
		["enchanted leather"] = 4,
	},
	["mighty iron hammer"] = {
		["iron bar"] = 6,
		["strong flux"] = 2,
		["elixir of ogre's strength"] = 1,
		["lesser moonstone"] = 2,
		["heavy grinding stone"] = 2,
		["medium leather"] = 2,
	},
	["mithril coif"] = {
		["mithril bar"] = 10,
		["mageweave cloth"] = 6,
	},
	["mithril scale bracers"] = {
		["mithril bar"] = 8,
		["citrine"] = 2,
	},
	["mithril scale pants"] = {
		["mithril bar"] = 12,
	},
	["mithril scale shoulders"] = {
		["mithril bar"] = 14,
		["thick leather"] = 4,
		["citrine"] = 4,
	},
	["mithril shield spike"] = {
		["mithril bar"] = 4,
		["truesilver bar"] = 2,
		["solid grinding stone"] = 4,
	},
	["mithril spurs"] = {
		["mithril bar"] = 4,
		["solid grinding stone"] = 3,
	},
	["moonsteel broadsword"] = {
		["steel bar"] = 8,
		["strong flux"] = 2,
		["heavy grinding stone"] = 2,
		["lesser moonstone"] = 3,
		["heavy leather"] = 3,
	},
	["nightfall"] = {
		["lava core"] = 8,
		["fiery core"] = 5,
		["arcanite bar"] = 10,
		["dark iron bar"] = 12,
		["huge emerald"] = 4,
	},
	["obsidian mail tunic"] = {
		["large obsidian shard"] = 15,
		["small obsidian shard"] = 36,
		["enchanted leather"] = 12,
		["guardian stone"] = 10,
		["azerothian diamond"] = 4,
	},
	["orcish war leggings"] = {
		["mithril bar"] = 12,
		["elemental earth"] = 1,
	},
	["ornate mithril boots"] = {
		["mithril bar"] = 14,
		["truesilver bar"] = 2,
		["thick leather"] = 4,
		["solid grinding stone"] = 1,
		["aquamarine"] = 1,
	},
	["ornate mithril breastplate"] = {
		["mithril bar"] = 16,
		["truesilver bar"] = 6,
		["heart of fire"] = 1,
		["solid grinding stone"] = 1,
	},
	["ornate mithril gloves"] = {
		["mithril bar"] = 10,
		["mageweave cloth"] = 6,
		["truesilver bar"] = 1,
		["solid grinding stone"] = 1,
	},
	["ornate mithril helm"] = {
		["mithril bar"] = 16,
		["truesilver bar"] = 2,
		["black pearl"] = 1,
		["solid grinding stone"] = 1,
	},
	["ornate mithril pants"] = {
		["mithril bar"] = 12,
		["truesilver bar"] = 1,
		["solid grinding stone"] = 1,
		["aquamarine"] = 1,
	},
	["ornate mithril shoulder"] = {
		["mithril bar"] = 12,
		["truesilver bar"] = 1,
		["thick leather"] = 6,
	},
	["ornate thorium handaxe"] = {
		["thorium bar"] = 20,
		["large opal"] = 2,
		["dense grinding stone"] = 2,
		["rugged leather"] = 4,
	},
	["patterned bronze bracers"] = {
		["bronze bar"] = 5,
		["coarse grinding stone"] = 2,
	},
	["pearl-handled dagger"] = {
		["bronze bar"] = 6,
		["strong flux"] = 1,
		["small lustrous pearl"] = 2,
		["coarse grinding stone"] = 2,
	},
	["persuader"] = {
		["arcanite bar"] = 15,
		["dark iron bar"] = 10,
		["essence of undeath"] = 20,
		["dark rune"] = 20,
		["desilsaur leather"] = 10,
		["skin of shadow"] = 2,
	},
	["phantom blade"] = {
		["mithril bar"] = 28,
		["breath of wind"] = 6,
		["truesilver bar"] = 8,
		["lesser invisibility potion"] = 2,
		["aquamarine"] = 6,
		["solid grinding stone"] = 4,
		["thick leather"] = 2,
	},
	["polished steel boots"] = {
		["steel bar"] = 8,
		["citrine"] = 1,
		["lesser moonstone"] = 1,
		["heavy grinding stone"] = 2,
	},
	["radiant belt"] = {
		["thorium bar"] = 10,
		["heart of fire"] = 2,
	},
	["radiant boots"] = {
		["thorium bar"] = 14,
		["heart of fire"] = 4,
	},
	["radiant breastplate"] = {
		["thorium bar"] = 18,
		["heart of fire"] = 2,
		["star ruby"] = 1,
	},
	["radiant circlet"] = {
		["thorium bar"] = 18,
		["heart of fire"] = 4,
	},
	["radiant gloves"] = {
		["thorium bar"] = 18,
		["heart of fire"] = 4,
	},
	["radiant leggings"] = {
		["thorium bar"] = 20,
		["heart of fire"] = 4,
	},
	["rough bronze boots"] = {
		["bronze bar"] = 6,
		["coarse grinding stone"] = 6,
	},
	["rough bronze cuirass"] = {
		["bronze bar"] = 7,
	},
	["rough bronze leggings"] = {
		["bronze bar"] = 6,
	},
	["rough bronze shoulders"] = {
		["bronze bar"] = 5,
		["shadowgem"] = 1,
		["coarse grinding stone"] = 1,
	},
	["rough copper vest"] = {
		["copper bar"] = 4,
	},
	["rough grinding stone"] = {
		["rough stone"] = 2,
	},
	["rough sharpening stone"] = {
		["rough stone"] = 1,
	},
	["rough weightstone"] = {
		["rough stone"] = 1,
		["linen cloth"] = 1,
	},
	["runed copper belt"] = {
		["copper bar"] = 10,
	},
	["runes copper bracers"] = {
		["copper bar"] = 10,
		["rough grinding stone"] = 3,
	},
	["runed copper breastplate"] = {
		["copper bar"] = 12,
		["shadowgem"] = 1,
		["rough grinding stone"] = 2,
	},
	["runed copper gauntlets"] = {
		["copper bar"] = 8,
		["rough grinding stone"] = 2,
	},
	["runed copper pants"] = {
		["copper bar"] = 8,
		["fine thread"] = 2,
		["rough grinding stone"] = 3,
	},
	["runed mithril hammer"] = {
		["mithril bar"] = 18,
		["core of earth"] = 2,
		["solid grinding stone"] = 1,
		["thick leather"] = 4,
	},
	["runic breastplate"] = {
		["thorium bar"] = 40,
		["arcanite bar"] = 2,
		["star ruby"] = 1,
	},
	["runic plate boots"] = {
		["thorium bar"] = 20,
		["arcanite bar"] = 2,
		["steel bar"] = 10,
	},
	["runic plate helm"] = {
		["thorium bar"] = 30,
		["arcanite bar"] = 2,
		["truesilver bar"] = 2,
		["huge emerald"] = 1,
	},
	["runic plate leggings"] = {
		["thorium bar"] = 40,
		["arcanite bar"] = 2,
		["star ruby"] = 1,
	},
	["runic plate shoulders"] = {
		["thorium bar"] = 20,
		["arcanite bar"] = 2,
		["gold bar"] = 6,
	},
	["sageblade"] = {
		["arcanite bar"] = 12,
		["nexus crystal"] = 2,
		["flask of supreme power"] = 2,
		["enchanted leather"] = 4,
	},
	["serenity"] = {
		["enchanted thorium bar"] = 6,
		["arcanite bar"] = 2,
		["powerful mojo"] = 4,
		["large opal"] = 2,
		["blue sapphire"] = 2,
		["huge emerald"] = 1,
	},
	["shining silver breastplate"] = {
		["bronze bar"] = 20,
		["moss agate"] = 2,
		["lesser moonstone"] = 2,
		["iridescent pearl"] = 2,
		["silver bar"] = 4,
	},
	["silver rod"] = {
		["silver bar"] = 1,
		["rough grinding stone"] = 2,
	},
	["silver skeleton key"] = {
		["silver bar"] = 1,
		["rough grinding stone"] = 1,
	},
	["silvered bronze boots"] = {
		["bronze bar"] = 6,
		["silver bar"] = 1,
		["coarse grinding stone"] = 2,
	},
	["silvered bronze breastplate"] = {
		["bronze bar"] = 10,
		["silver bar"] = 2,
		["coarse grinding stone"] = 2,
		["lesser moonstone"] = 1,
	},
	["silvered bronze gauntlets"] = {
		["bronze bar"] = 8,
		["silver bar"] = 1,
		["coarse grinding stone"] = 2,
	},
	["silvered bronze leggings"] = {
		["bronze bar"] = 12,
		["silver bar"] = 4,
		["coarse grinding stone"] = 2,
	},
	["silvered bronze shoulders"] = {
		["bronze bar"] = 8,
		["silver bar"] = 2,
		["coarse grinding stone"] = 2,
	},
	["solid grinding stone"] = {
		["solid stone"] = 4,
	},
	["solid sharpening stone"] = {
		["solid stone"] = 1,
	},
	["solid weightstone"] = {
		["solid stone"] = 1,
		["silk cloth"] = 1,
	},
	["steel breastplate"] = {
		["steel bar"] = 16,
		["heavy grinding stone"] = 3,
	},
	["steel plate helm"] = {
		["steel bar"] = 14,
		["solid grinding stone"] = 1,
	},
	["steel weapon chain"] = {
		["steel bar"] = 8,
		["heavy grinding stone"] = 2,
		["heavy leather"] = 4,
	},
	["storm gauntlets"] = {
		["thorium bar"] = 20,
		["enchanted thorium bar"] = 4,
		["essence of water"] = 4,
		["blue sapphire"] = 4,
	},
	["stronghold gauntlets"] = {
		["arcanite bar"] = 15,
		["enchanted thorium bar"] = 20,
		["essence of earth"] = 10,
		["blue sapphire"] = 4,
		["large opal"] = 4,
	},
	["sulfuron hammer"] = {
		["sulfuron ingot"] = 8,
		["dark iron bar"] = 20,
		["arcanite bar"] = 50,
		["essence of fire"] = 25,
		["blood of the mountain"] = 10,
		["lava core"] = 10,
		["fiery core"] = 10,
	},
	["the shatterer"] = {
		["mithril bar"] = 24,
		["core of earth"] = 4,
		["truesilver bar"] = 6,
		["citrine"] = 5,
		["jade"] = 5,
		["solid grinding stone"] = 4,
		["thick leather"] = 4,
	},
	["thick obsidian breastplate"] = {
		["large obsidian shard"] = 18,
		["small obsidian shard"] = 40,
		["enchanted thorium"] = 12,
		["essence of earth"] = 10,
		["huge emerald"] = 4,
	},
	["thick war axe"] = {
		["copper bar"] = 10,
		["weak flux"] = 2,
		["silver bar"] = 2,
		["rough grinding stone"] = 2,
		["light leather"] = 2,
	},
	["thorium armor"] = {
		["thorium bar"] = 16,
		["blue sapphire"] = 1,
		["yellow power crystal"] = 4,
	},
	["thorium belt"] = {
		["thorium bar"] = 12,
		["red power crystal"] = 4,
	},
	["thorium boots"] = {
		["thorium bar"] = 20,
		["rugged leather"] = 8,
		["green power crystal"] = 4,
	},
	["thorium bracers"] = {
		["thorium bar"] = 12,
		["blue power crystal"] = 4,
	},
	["thorium helm"] = {
		["thorium bar"] = 24,
		["star ruby"] = 1,
		["yellow power crystal"] = 4,
	},
	["thorium leggings"] = {
		["thorium bar"] = 26,
		["red power crystal"] = 4,
	},
	["thorium shield spike"] = {
		["thorium bar"] = 4,
		["dense grinding stone"] = 4,
		["essence of earth"] = 2,
	},
	["titanic leggings"] = {
		["arcanite bar"] = 12,
		["enchanted thorium bar"] = 20,
		["essence of earth"] = 10,
		["flask of the titans"] = 2,
	},
	["tranquility"] = {
		["enchanted thorium bar"] = 6,
		["arcanite bar"] = 2,
		["powerful mojo"] = 4,
		["large opal"] = 2,
		["blue sapphire"] = 2,
		["huge emeral"] = 1,
	},
	["truesilver breastplate"] = {
		["mithril bar"] = 12,
		["truesilver bar"] = 24,
		["star ruby"] = 4,
		["black pearl"] = 4,
		["solid grinding stone"] = 2,
	},
	["truesilver champion"] = {
		["mithril bar"] = 30,
		["truesilver bar"] = 16,
		["star ruby"] = 6,
		["breath of wind"] = 4,
		["solid grinding stone"] = 8,
		["thick leather"] = 6,
	},
	["truesilver gauntlets"] = {
		["mithril bar"] = 10,
		["truesilver bar"] = 8,
		["aquamarine"] = 3,
		["citrine"] = 3,
		["guardian gloves"] = 1,
		["solid grinding stone"] = 2,
	},
	["truesilver rod"] = {
		["truesilver bar"] = 1,
		["heavy grinding stone"] = 1,
	},
	["truesilver skeleton key"] = {
		["truesilver bar"] = 1,
		["solid grinding stone"] = 1,
	},
	["volcanic hammer"] = {
		["thorium bar"] = 30,
		["heart of fire"] = 4,
		["star ruby"] = 4,
		["rugged leather"] = 4,
	},
	["whitesoul helm"] = {
		["thorium bar"] = 20,
		["enchanted thorium bar"] = 4,
		["truesilver bar"] = 6,
		["gold bar"] = 6,
		["azerothian diamond"] = 2,
	},
	["wildthorn mail"] = {
		["thorium bar"] = 40,
		["enchanted thorium bar"] = 2,
		["living essence"] = 4,
		["kingsblood"] = 4,
		["huge emerald"] = 1,
	},
	-- ENCHANTING
	["dream dust"] = {},
	["enchanted leather"] = {
		["rugged leather"] = 1,
		["lesser eternal essence"] = 1,
	},
	["enchanted thorium bar"] = {
		["thorium bar"] = 1,
		["dream dust"] = 3,
	},
	["greater astral essence"] = {},
	["greater eternal essence"] = {},
	["greater magic essence"] = {},
	["greater mystic essence"] = {},
	["illusion dust"] = {},
	["large brilliant shard"] = {},
	["lesser eternal essence"] = {},
	["lesser magic essence"] = {},
	["nexus crystal"] = {},
	["runed arcanite rod"] = {
		["arcanite rod"] = 1,
		["golden pearl"] = 1,
		["illusion dust"] = 10,
		["greater eternal essence"] = 4,
		["small brilliant shard"] = 4,
		["large brilliant shard"] = 2,
	},
	["runed copper rod"] = {
		["copper rod"] = 1,
		["strange dust"] = 1,
	},
	["runed golden rod"] = {
		["golden rod"] = 1,
		["iridescent pearl"] = 1,
		["greater astral essence"] = 2,
		["soul dust"] = 2,
	},
	["runed silver rod"] = {
		["silver rod"] = 1,
		["strange dust"] = 6,
		["greater magic essence"] = 3,
		["shadow gem"] = 1,
	},
	["runed truesilver rod"] = {
		["truesilver rod"] = 1,
		["black pearl"] = 1,
		["greater mystic essence"] = 2,
		["vision dust"] = 2,
	},
	["small brilliant shard"] = {},
	["soul dust"] = {},
	["strange dust"] = {},
	["vision dust"] = {},
	-- ENGINEERING
	["accurate scope"] = {
		["bronze tube"] = 1,
		["jade"] = 1,
		["citrine"] = 1,
	},
	["advanced target dummy"] = {
		["iron strut"] = 1,
		["bronze framework"] = 1,
		["gyrochronatom"] = 1,
		["heavy leather"] = 4,
	},
	["aquadynamic fish attractor"] = {
		["bronze bar"] = 2,
		["nightcrawlers"] = 1,
		["coarse blasting powder"] = 1,
	},
	["arcane bomb"] = {
		["delicate arcanite converter"] = 1,
		["thorium bar"] = 3,
		["runecloth"] = 1,
	},
	["arcanite dragonling"] = {
		["mithril mechanical dragonling"] = 1,
		["delicate arcanite converter"] = 8,
		["enchanted thorium bar"] = 10,
		["thorium widget"] = 6,
		["gold power core"] = 4,
		["enchanted leather"] = 6,
	},
	["arclight spanner"] = {
		["copper bar"] = 6,
	},
	["big bronze bomb"] = {
		["heavy blasting powder"] = 2,
		["bronze bar"] = 3,
		["silver contact"] = 1,
	},
	["big iron bomb"] = {
		["iron bar"] = 3,
		["heavy blasting powder"] = 3,
		["silver contact"] = 1,
	},
	["biznicks 247x128 accurascope"] = {
		["lava core"] = 2,
		["essence of earth"] = 2,
		["delicate arcanite converter"] = 4,
		["dark iron bar"] = 6,
		["thorium tube"] = 1,
	},
	["bloodvine goggles"] = {
		["bloodvine"] = 4,
		["souldarite"] = 5,
		["delicate arcanite converter"] = 2,
		["powerful mojo"] = 8,
		["enchanted leather"] = 4,
	},
	["bloodvine lens"] = {
		["bloodvine"] = 5,
		["souldarite"] = 5,
		["delicate arcanite converter"] = 1,
		["powerful mojo"] = 8,
		["enchanted leather"] = 4,
	},
	["blue firework"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["blue rocket cluster"] = {
		["solid blasting powder"] = 1,
		["thick leather"] = 1,
	},
	["bright-eye goggles"] = {
		["heavy leather"] = 6,
		["citrine"] = 2,
	},
	["bronze framework"] = {
		["bronze bar"] = 2,
		["medium leather"] = 1,
		["wool cloth"] = 1,
	},
	["bronze tube"] = {
		["bronze bar"] = 2,
		["weak flux"] = 1,
	},
	["catseye ultra goggles"] = {
		["thick leather"] = 4,
		["aquamarine"] = 2,
		["catseye elixir"] = 1,
	},
	["cluster launcher"] = {
		["inlaid mithril cylinder"] = 4,
		["goblin rocket fuel"] = 4,
		["truesilver transformer"] = 2,
		["mithril casing"] = 1,
	},
	["coarse blasting powder"] = {
		["coarse stone"] = 2,
	},
	["coarse dynamite"] = {
		["coarse blasting powder"] = 3,
		["linen cloth"] = 1,
	},
	["compact harvest reaper kit"] = {
		["iron strut"] = 2,
		["bronze framework"] = 1,
		["gyrochronatom"] = 2,
		["heavy leather"] = 4,
	},
	["copper modulator"] = {
		["handful of copper bolts"] = 2,
		["copper bar"] = 1,
		["linen cloth"] = 2,
	},
	["copper tube"] = {
		["copper bar"] = 2,
		["weak flux"] = 1,
	},
	["core marksman rifle"] = {
		["fiery core"] = 4,
		["lava core"] = 2,
		["arcanite bar"] = 6,
		["delicate arcanite converter"] = 2,
		["thorium tube"] = 2,
	},
	["crafted heavy shot"] = {
		["coarse blasting powder"] = 1,
		["copper bar"] = 1,
	},
	["crafted light shot"] = {
		["rough blasting powder"] = 1,
		["copper bar"] = 1,
	},
	["crafted solid shot"] = {
		["heavy blasting powder"] = 1,
		["bronze bar"] = 1,
	},
	["craftsman's monocle"] = {
		["heavy leather"] = 6,
		["citrine"] = 2,
	},
	["crude scope"] = {
		["copper tube"] = 1,
		["malachite"] = 1,
		["handful of copper bolts"] = 1,
	},
	["dark iron bomb"] = {
		["thorium widget"] = 2,
		["dark iron bar"] = 1,
		["dense blasting powder"] = 3,
		["runecloth"] = 3,
	},
	["dark iron rifle"] = {
		["thorium tube"] = 2,
		["dark iron bar"] = 6,
		["deadly scope"] = 2,
		["blue sapphire"] = 2,
		["large opal"] = 2,
		["rugged leather"] = 4,
	},
	["deadly blunderbuss"] = {
		["copper tube"] = 2,
		["handful of copper bolts"] = 4,
		["wooden stock"] = 1,
		["medium leather"] = 2,
	},
	["deadly scope"] = {
		["mithril tube"] = 1,
		["aquamarine"] = 2,
		["thick leather"] = 2,
	},
	["deepdive helmet"] = {
		["mithril bar"] = 8,
		["mithril casing"] = 1,
		["truesilver bar"] = 1,
		["tigerseye"] = 4,
		["malachite"] = 4,
	},
	["delicate arcanite converter"] = {
		["arcanite bar"] = 1,
		["ironweb spider silk"] = 1,
	},
	["dense blasting powder"] = {
		["dense stone"] = 2,
	},
	["dense dynamite"] = {
		["dense blasting powder"] = 2,
		["runecloth"] = 3,
	},
	["dimensional ripper - everlook"] = {
		["mithril bar"] = 10,
		["truesilver transformer"] = 1,
		["heart of fire"] = 4,
		["star ruby"] = 1,
		["the big one"] = 1,
	},
	["discombobulator ray"] = {
		["whirring bronze gizmo"] = 3,
		["silk cloth"] = 2,
		["jade"] = 1,
		["bronze tube"] = 1,
	},
	["explosive sheep"] = {
		["bronze framework"] = 1,
		["whirring bronze gizmo"] = 1,
		["heavy blasting powder"] = 2,
		["wool cloth"] = 2,
	},
	["ez-thro dynamite"] = {
		["coarse blasting powder"] = 4,
		["wool cloth"] = 1,
	},
	["ez-thro dynamite ii"] = {
		["solid blasting powder"] = 1,
		["mageweave cloth"] = 2,
	},
	["field repair bot 74a"] = {
		["thorium bar"] = 12,
		["rugged leather"] = 4,
		["fused wiring"] = 1,
		["elemental earth"] = 2,
		["elemental fire"] = 1,
	},
	["fiery core sharpshooter rifle"] = {
		["fiery core"] = 4,
		["lava core"] = 2,
		["arcanite bar"] = 6,
		["delicate arcanite converter"] = 2,
		["thorium tube"] = 2,
	},
	["fire googles"] = {
		["green tinted goggles"] = 1,
		["citrine"] = 2,
		["elemental fire"] = 2,
		["heavy leather"] = 4,
	},
	["firework launcher"] = {
		["inlaid mithril cylinder"] = 1,
		["goblin rocket fuel"] = 1,
		["unstable trigger"] = 1,
		["mithril casing"] = 1,
	},
	["flame deflector"] = {
		["whirring bronze gizmo"] = 1,
		["small flame sac"] = 1,
	},
	["flash bomb"] = {
		["blue pearl"] = 1,
		["heavy blasting powder"] = 1,
		["silk cloth"] = 1,
	},
	["flawless arcanite rifle"] = {
		["arcanite bar"] = 10,
		["thorium tube"] = 2,
		["essence of fire"] = 2,
		["essence of earth"] = 2,
		["azerothian diamond"] = 2,
		["enchanted leather"] = 2,
	},
	["flying tiger goggles"] = {
		["light leather"] = 6,
		["tigerseye"] = 2,
	},
	["force reactive disk"] = {
		["arcanite bar"] = 6,
		["delicate arcanite converter"] = 2,
		["essence of air"] = 8,
		["living essence"] = 12,
		["essence of earth"] = 8,
	},
	["gnomish alarm-o-bot"] = {
		["thorium bar"] = 4,
		["thorium widget"] = 2,
		["rugged leather"] = 4,
		["star ruby"] = 1,
		["fused wiring"] = 1,
	},
	["gnomisch battle chicken"] = {
		["mithril casing"] = 1,
		["truesilver bar"] = 6,
		["mithril bar"] = 6,
		["inlaid mithril cylinder"] = 2,
		["gold power core"] = 1,
		["jade"] = 2,
	},
	["gnomisch cloaking device"] = {
		["gyrochronatom"] = 4,
		["jade"] = 2,
		["lesser moonstone"] = 2,
		["citrine"] = 2,
		["fused wiring"] = 1,
	},
	["gnomish death ray"] = {
		["mithril tube"] = 2,
		["unstable trigger"] = 1,
		["essence of undeath"] = 1,
		["ichor of undeath"] = 4,
		["inlaid mithril cylinder"] = 1,
	},
	["gnomish goggles"] = {
		["fire goggles"] = 1,
		["mithril tube"] = 1,
		["gold power core"] = 2,
		["flask of mojo"] = 2,
		["heavy leather"] = 2,
	},
	["gnomish harm prevention belt"] = {
		["dusky belt"] = 1,
		["mithril bar"] = 4,
		["truesilver bar"] = 2,
		["unstable trigger"] = 1,
		["aquamarine"] = 2,
	},
	["gnomish mind control cap"] = {
		["mithril bar"] = 10,
		["truesilver bar"] = 4,
		["gold power core"] = 1,
		["star ruby"] = 2,
		["mageweave cloth"] = 4,
	},
	["gnomishnet-o-matic projector"] = {
		["mithril tube"] = 1,
		["shadow silk"] = 2,
		["thick spider silk"] = 4,
		["solid blasting powder"] = 2,
		["mithril bar"] = 4,
	},
	["gnomish rocket boots"] = {
		["black mageweave boots"] = 1,
		["mithril tube"] = 2,
		["heavy leather"] = 4,
		["solid blasting powder"] = 8,
		["gyrochronatom"] = 4,
	},
	["gnomish shrink ray"] = {
		["mithril tube"] = 1,
		["unstable trigger"] = 1,
		["mithril bar"] = 4,
		["flask of mojo"] = 4,
		["jade"] = 2,
	},
	["gnomish universal remote"] = {
		["bronze bar"] = 6,
		["whirring bronze gizmo"] = 1,
		["flask of oil"] = 2,
		["tigerseye"] = 1,
		["malachite"] = 1,
	},
	["goblin bomb dispenser"] = {
		["mithril casing"] = 2,
		["solid blasting powder"] = 4,
		["truesilver bar"] = 6,
		["unstable trigger"] = 1,
		["accurate scope"] = 2,
	},
	["goblin construction helmet"] = {
		["mithril bar"] = 8,
		["citrine"] = 1,
		["elemental fire"] = 4,
	},
	["goblin dragon gun"] = {
		["mithril tube"] = 2,
		["goblin rocket fuel"] = 4,
		["mithril bar"] = 6,
		["truesilver bar"] = 6,
		["unstable trigger"] = 1,
	},
	["goblin jumper cables"] = {
		["iron bar"] = 6,
		["whirring bronze gizmo"] = 2,
		["flask of oil"] = 2,
		["silk cloth"] = 2,
		["shadow gem"] = 2,
		["fused wiring"] = 1,
	},
	["goblin jumper cables xl"] = {
		["thorium widget"] = 2,
		["truesilver transformer"] = 2,
		["fused wiring"] = 2,
		["ironweb spider silk"] = 2,
		["star ruby"] = 2,
	},
	["goblin land mine"] = {
		["heavy blasting powder"] = 3,
		["iron bar"] = 2,
		["gyrochronatom"] = 1,
	},
	["goblin mining helmet"] = {
		["mithril bar"] = 8,
		["citrine"] = 1,
		["elemental earth"] = 4,
	},
	["goblin mortar"] = {
		["mithril tube"] = 2,
		["mithril bar"] = 4,
		["solid blasting powder"] = 5,
		["gold power core"] = 1,
		["elemental fire"] = 1,
	},
	["goblin rocket boots"] = {
		["black mageweave boots"] = 1,
		["mithril tube"] = 2,
		["heavy leather"] = 4,
		["goblin rocket fuel"] = 2,
		["unstable trigger"] = 1,
	},
	["goblin rocket helmet"] = {
		["goblin construction helmet"] = 1,
		["goblin rocket fuel"] = 4,
		["mithril bar"] = 4,
		["unstable trigger"] = 1,
	},
	["goblin sapper charge"] = {
		["mageweave cloth"] = 1,
		["unstable trigger"] = 1,
		["solid blasting powder"] = 3,
	},
	["gold power core"] = {
		["gold bar"] = 1,
	},
	["green firework"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["green lens"] = {
		["thick leather"] = 8,
		["jade"] = 3,
		["aquamarine"] = 3,
		["heart of the wild"] = 2,
		["wildvine"] = 2,
	},
	["green rocket cluster"] = {
		["solid blasting powder"] = 1,
		["thick leather"] = 1,
	},
	["green tinted goggles"] = {
		["medium leather"] = 4,
		["moss agate"] = 2,
		["flying tiger goggles"] = 1,
	},
	["gyrochronatom"] = {
		["iron bar"] = 1,
		["gold power core"] = 1,
	},
	["gyrofreeze ice reflector"] = {
		["thorium widget"] = 6,
		["truesilver transformer"] = 2,
		["blue sapphire"] = 2,
		["essence of fire"] = 4,
		["frost oil"] = 2,
		["icecap"] = 4,
	},
	["gyromatic micro-adjustor"] = {
		["steel bar"] = 4,
	},
	["handful of copper bolts"] = {
		["copper bar"] = 1,
	},
	["heavy blasting powder"] = {
		["heavy stone"] = 1,
	},
	["heavy dynamite"] = {
		["heavy blasting powder"] = 2,
		["wool cloth"] = 1,
	},
	["hi-explosive bomb"] = {
		["mithril casing"] = 2,
		["unstable trigger"] = 1,
		["solid blasting powder"] = 2,
	},
	["hi-impact mithril slugs"] = {
		["mithril bar"] = 1,
		["solid blasting powder"] = 1,
	},
	["hyper-radiant flame reflector"] = {
		["dark iron bar"] = 4,
		["truesilver transformer"] = 3,
		["essence of water"] = 6,
		["star ruby"] = 4,
		["azerothian diamond"] = 2,
	},
	["ice deflector"] = {
		["whirring bronze gizmo"] = 1,
		["frost oil"] = 1,
	},
	["iron grenade"] = {
		["iron bar"] = 1,
		["heavy blasting powder"] = 1,
		["silk cloth"] = 1,
	},
	["iron strut"] = {
		["iron bar"] = 2,
	},
	["large blue rocket"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["large blue rocket cluster"] = {
		["dense blasting powder"] = 1,
		["rugged leather"] = 1,
	},
	["large copper bomb"] = {
		["copper bar"] = 3,
		["coarse blasting powder"] = 4,
		["silver contact"] = 1,
	},
	["large green rocket"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["large green rocket cluster"] = {
		["dense blasting powder"] = 1,
		["rugged leather"] = 1,
	},
	["large red rocket"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["large red rocket cluster"] = {
		["dense blasting powder"] = 1,
		["rugged leather"] = 1,
	},
	["large seaforium charge"] = {
		["solid blasting powder"] = 2,
		["heavy leather"] = 2,
		["refreshing spring water"] = 1,
	},
	["lifelike mechanical toad"] = {
		["living essence"] = 1,
		["thorium widget"] = 4,
		["gold power core"] = 1,
		["rugged leather"] = 1,
	},
	["lil' smoky"] = {
		["core of earth"] = 1,
		["gyrochronatom"] = 2,
		["fused wiring"] = 1,
		["mithril bar"] = 2,
		["truesilver bar"] = 1,
	},
	["lovingly crafted boomstick"] = {
		["bronze tube"] = 2,
		["handful of copper bolts"] = 2,
		["heavy stock"] = 1,
		["moss agate"] = 3,
	},
	["major recombobulator"] = {
		["thorium tube"] = 2,
		["truesilver transformer"] = 1,
		["runecloth"] = 2,
	},
	["master engineer's goggles"] = {
		["fire goggles"] = 1,
		["jade"] = 2,
		["enchanted leather"] = 4,
	},
	["masterwork target dummy"] = {
		["mithril casing"] = 1,
		["thorium tube"] = 1,
		["thorium widget"] = 2,
		["truesilver bar"] = 1,
		["rugged leather"] = 2,
		["runecloth"] = 4,
	},
	["mechanical dragonling"] = {
		["bronze framework"] = 1,
		["iron strut"] = 4,
		["gyrochronatom"] = 4,
		["citrine"] = 2,
		["fused wiring"] = 1,
	},
	["mechanical repair kit"] = {
		["mithril bar"] = 1,
		["mageweave cloth"] = 1,
		["solid blasting powder"] = 1,
	},
	["mechanical squirrel box"] = {
		["copper modulator"] = 1,
		["handful of copper bolts"] = 1,
		["copper bar"] = 1,
		["malachite"] = 2,
	},
	["minor recombobulator"] = {
		["bronze tube"] = 1,
		["whirring bronze gizmo"] = 2,
		["medium leather"] = 2,
		["moss agate"] = 1,
	},
	["mithril blunderbuss"] = {
		["mithril tube"] = 1,
		["unstable trigger"] = 1,
		["heavy stock"] = 1,
		["mithril bar"] = 4,
		["elemental fire"] = 2,
	},
	["mithril casing"] = {
		["mithril bar"] = 3,
	},
	["mithril frag bomb"] = {
		["mithril casing"] = 1,
		["unstable trigger"] = 1,
		["solid blasting powder"] = 1,
	},
	["mithril gyro-shot"] = {
		["mithril bar"] = 2,
		["solid blasting powder"] = 2,
	},
	["mithri heavy-bore rifle"] = {
		["mithril tube"] = 2,
		["unstable trigger"] = 1,
		["heavy stock"] = 1,
		["mithril bar"] = 6,
		["citrine"] = 2,
	},
	["mithril mechanical dragonling"] = {
		["mithril bar"] = 14,
		["heart of fire"] = 4,
		["truesilver bar"] = 4,
		["inlaid mithril cylinder"] = 2,
		["goblin rocket fuel"] = 2,
		["star ruby"] = 2,
	},
	["mithril tube"] = {
		["mithril bar"] = 3,
	},
	["moonsight rifle"] = {
		["bronze tube"] = 3,
		["whirring bronze gizmo"] = 3,
		["heavy stock"] = 1,
		["lesser moonstone"] = 2,
	},
	["ornate spyglass"] = {
		["bronze tube"] = 2,
		["whirring bronze gizmo"] = 2,
		["copper modulator"] = 1,
		["moss agate"] = 1,
	},
	["parachute cloak"] = {
		["bolt of mageweave"] = 4,
		["shadow silk"] = 2,
		["unstable trigger"] = 1,
		["solid blasting powder"] = 4,
	},
	["pet bombling"] = {
		["big iron bomb"] = 1,
		["heart of fire"] = 1,
		["fused wiring"] = 1,
		["mithril bar"] = 6,
	},
	["plans: inlaid mithril cylinder"] = {
		["blank parchment"] = 1,
		["engineer's ink"] = 1,
	},
	["portable bronze mortar"] = {
		["bronze tube"] = 4,
		["iron strut"] = 1,
		["heavy blasting powder"] = 4,
		["medium leather"] = 4,
	},
	["powerful seaforium charge"] = {
		["thorium widget"] = 2,
		["dense blasting powder"] = 3,
		["rugged leather"] = 2,
		["refreshing spring water"] = 1,
	},
	["practice lock"] = {
		["bronze bar"] = 1,
		["handful of copper bolts"] = 2,
		["weak flux"] = 1,
	},
	["recipe: goblin rocket fuel"] = {
		["blank parchment"] = 1,
		["engineer's ink"] = 1,
	},
	["red firework"] = {
		["heavy blasting powder"] = 1,
		["heavy leather"] = 1,
	},
	["red rocket cluster"] = {
		["solid blasting powder"] = 1,
		["thick leather"] = 1,
	},
	["rose colored goggles"] = {
		["thick leather"] = 6,
		["star ruby"] = 2,
	},
	["rough blasting powder"] = {
		["rough stone"] = 1,
	},
	["rough boomstick"] = {
		["copper tube"] = 1,
		["handful of copper bolts"] = 1,
		["wooden stock"] = 1,
	},
	["rough copper bomb"] = {
		["copper bar"] = 1,
		["handful of copper bolts"] = 1,
		["rough blasting powder"] = 2,
		["linen cloth"] = 1,
	},
	["rough dynamite"] = {
		["rough blasting powder"] = 2,
		["linen cloth"] = 1,
	},
	["salt shaker"] = {
		["mithril casing"] = 1,
		["thorium bar"] = 6,
		["gold power core"] = 1,
		["unstable trigger"] = 4,
	},
	["shadow goggles"] = {
		["medium leather"] = 4,
		["shadow gem"] = 2,
	},
	["silver contact"] = {
		["silver bar"] = 1,
	},
	["silver-plated shotgun"] = {
		["bronze tube"] = 2,
		["whirring bronze gizmo"] = 2,
		["heavy stock"] = 1,
		["silver bar"] = 3,
	},
	["small blue rocket"] = {
		["coarse blasting powder"] = 1,
		["medium leather"] = 1,
	},
	["small bronze bomb"] = {
		["coarse blasting powder"] = 4,
		["bronze bar"] = 2,
		["silver contact"] = 1,
		["wool cloth"] = 1,
	},
	["small green rocket"] = {
		["coarse blasting powder"] = 1,
		["medium leather"] = 1,
	},
	["small red rocket"] = {
		["coarse blasting powder"] = 1,
		["medium leather"] = 1,
	},
	["small seaforium charge"] = {
		["coarse blasting powder"] = 2,
		["copper modulator"] = 1,
		["light leather"] = 1,
		["refreshing spring water"] = 1,
	},
	["snake burst firework"] = {
		["dense blasting powder"] = 2,
		["runecloth"] = 2,
		["deeprock salt"] = 1,
	},
	["sniper scope"] = {
		["mithril tube"] = 1,
		["star ruby"] = 1,
		["truesilver bar"] = 2,
	},
	["snow master 9000"] = {
		["mithril bar"] = 8,
		["gyrochronatom"] = 4,
		["snowball"] = 4,
		["frost oil"] = 1,
	},
	["solid blasting powder"] = {
		["solid stone"] = 2,
	},
	["solid dynamite"] = {
		["solid blasting powder"] = 1,
		["silk cloth"] = 1,
	},
	["spellpower goggles xtreme"] = {
		["thick leather"] = 4,
		["star ruby"] = 2,
	},
	["spellpower goggles xtreme plus"] = {
		["spellpower goggles xtreme"] = 1,
		["star ruby"] = 4,
		["enchanted leather"] = 2,
		["runecloth"] = 8,
	},
	["standard scope"] = {
		["bronze tube"] = 1,
		["moss agate"] = 1,
	},
	["steam tonk controller"] = {
		["thorium widget"] = 2,
		["mithril casing"] = 1,
		["gold power core"] = 1,
	},
	["target dummy"] = {
		["copper modulator"] = 1,
		["handful of copper bolts"] = 2,
		["bronze bar"] = 1,
		["wool cloth"] = 1,
	},
	["the big one"] = {
		["mithril casing"] = 1,
		["goblin rocket fuel"] = 1,
		["solid dynamite"] = 6,
		["unstable trigger"] = 1,
	},
	["the mortar: reloaded"] = {
		["mithril tube"] = 1,
		["mithril bar"] = 1,
		["solid blasting powder"] = 3,
	},
	["thorium grenade"] = {
		["thorium widget"] = 1,
		["thorium bar"] = 3,
		["dense blasting powder"] = 3,
		["runecloth"] = 3,
	},
	["thorium rifle"] = {
		["mithril tube"] = 2,
		["mithril casing"] = 2,
		["thorium widget"] = 2,
		["thorium bar"] = 4,
		["deadly scope"] = 1,
	},
	["thorium shells"] = {
		["thorium bar"] = 2,
		["dense blasting powder"] = 1,
	},
	["thorium tube"] = {
		["thorium bar"] = 6,
	},
	["thorium widget"] = {
		["thorium bar"] = 3,
		["runecloth"] = 1,
	},
	["tranquil mechanical yeti"] = {
		["cured rugged hide"] = 1,
		["thorium widget"] = 4,
		["globe of water"] = 2,
		["truesilver transformer"] = 2,
		["gold power core"] = 1,
	},
	["truesilver transformer"] = {
		["truesilver bar"] = 2,
		["elemental earth"] = 2,
		["elemental air"] = 1,
	},
	["ultra-flash shadow reflector"] = {
		["dark iron bar"] = 8,
		["truesilver transformer"] = 4,
		["living essence"] = 6,
		["essence of undeath"] = 4,
		["azerothian diamond"] = 2,
		["large opal"] = 2,
	},
	["ultrasafe transporter: gadgetzan"] = {
		["mithril bar"] = 12,
		["truesilver transformer"] = 2,
		["core of earth"] = 4,
		["globe of water"] = 2,
		["aquamarine"] = 4,
		["inlaid mithril cylinder"] = 1,
	},
	["unstable trigger"] = {
		["mageweave cloth"] = 1,
		["solid blasting powder"] = 1,
		["mithril bar"] = 1,
	},
	["voice amplification modulator"] = {
		["delicate arcanite converter"] = 2,
		["gold power core"] = 1,
		["thorium widget"] = 1,
		["large opal"] = 1,
	},
	["whirring bronze gizmo"] = {
		["bronze bar"] = 2,
		["wool cloth"] = 1,
	},
	["world enlarger"] = {
		["mithril casing"] = 1,
		["thorium widget"] = 2,
		["gold power core"] = 1,
		["unstable trigget"] = 1,
		["citrine"] = 1,
	},
	-- LEATHERWORKING
	["green leather armor"] = {
		["heavy leather"] = 9,
		["green dye"] = 2,
		["fine thread"] = 4,
	},
	-- TAILORING
	["black mageweave boots"] = {
		["bolt of mageweave"] = 3,
		["heavy silken thread"] = 2,
		["thick leather"] = 2,
	},
	["dusky belt"] = {
		["heavy leather"] = 10,
		["bolt of silk cloth"] = 2,
		["black dye"] = 2,
		["iron buckle"] = 1,
	},
	["guardian gloves"] = {
		["heavy leather"] = 4,
		["cured heavy hide"] = 1,
		["silken thread"] = 1,
	},
}
